// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.0--rc2
// source: phase.proto

package phase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PhaseEqualibrium_Divide_FullMethodName   = "/phase_proto.PhaseEqualibrium/Divide"
	PhaseEqualibrium_Multiply_FullMethodName = "/phase_proto.PhaseEqualibrium/Multiply"
)

// PhaseEqualibriumClient is the client API for PhaseEqualibrium service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhaseEqualibriumClient interface {
	Divide(ctx context.Context, in *DivideRequest, opts ...grpc.CallOption) (*Response, error)
	Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*Response, error)
}

type phaseEqualibriumClient struct {
	cc grpc.ClientConnInterface
}

func NewPhaseEqualibriumClient(cc grpc.ClientConnInterface) PhaseEqualibriumClient {
	return &phaseEqualibriumClient{cc}
}

func (c *phaseEqualibriumClient) Divide(ctx context.Context, in *DivideRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, PhaseEqualibrium_Divide_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phaseEqualibriumClient) Multiply(ctx context.Context, in *MultiplyRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, PhaseEqualibrium_Multiply_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhaseEqualibriumServer is the server API for PhaseEqualibrium service.
// All implementations must embed UnimplementedPhaseEqualibriumServer
// for forward compatibility
type PhaseEqualibriumServer interface {
	Divide(context.Context, *DivideRequest) (*Response, error)
	Multiply(context.Context, *MultiplyRequest) (*Response, error)
	mustEmbedUnimplementedPhaseEqualibriumServer()
}

// UnimplementedPhaseEqualibriumServer must be embedded to have forward compatible implementations.
type UnimplementedPhaseEqualibriumServer struct {
}

func (UnimplementedPhaseEqualibriumServer) Divide(context.Context, *DivideRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Divide not implemented")
}
func (UnimplementedPhaseEqualibriumServer) Multiply(context.Context, *MultiplyRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Multiply not implemented")
}
func (UnimplementedPhaseEqualibriumServer) mustEmbedUnimplementedPhaseEqualibriumServer() {}

// UnsafePhaseEqualibriumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhaseEqualibriumServer will
// result in compilation errors.
type UnsafePhaseEqualibriumServer interface {
	mustEmbedUnimplementedPhaseEqualibriumServer()
}

func RegisterPhaseEqualibriumServer(s grpc.ServiceRegistrar, srv PhaseEqualibriumServer) {
	s.RegisterService(&PhaseEqualibrium_ServiceDesc, srv)
}

func _PhaseEqualibrium_Divide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DivideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseEqualibriumServer).Divide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseEqualibrium_Divide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseEqualibriumServer).Divide(ctx, req.(*DivideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PhaseEqualibrium_Multiply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhaseEqualibriumServer).Multiply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PhaseEqualibrium_Multiply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhaseEqualibriumServer).Multiply(ctx, req.(*MultiplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhaseEqualibrium_ServiceDesc is the grpc.ServiceDesc for PhaseEqualibrium service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhaseEqualibrium_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phase_proto.PhaseEqualibrium",
	HandlerType: (*PhaseEqualibriumServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Divide",
			Handler:    _PhaseEqualibrium_Divide_Handler,
		},
		{
			MethodName: "Multiply",
			Handler:    _PhaseEqualibrium_Multiply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "phase.proto",
}
